spring.application.name=quran-app-backend

spring.datasource.url=jdbc:h2:file:./data/quranapp;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8010

quran.api.text-base-url=https://api.alquran.cloud/v1
quran.api.text-edition=en.sahih
quran.api.arabic-edition=quran-uthmani
quran.api.tafsir-base-url=https://api.quran.com/api/v4


## placeholder to check translation
quran.api.tafsir-resource-id=169